/**
 * Utility for Audio Pronunciation in Leksika Nusantara
 * Powered by Gemini AI TTS for authentic regional voice pronunciation,
 * with graceful fallback to browser Web Speech API & Web Audio chime.
 */

export async function speakWord(
  text: string,
  langCode: string = 'id-ID',
  onEnd?: () => void,
  langName?: string
): Promise<void> {
  if (!text || !text.trim()) {
    if (onEnd) onEnd();
    return;
  }

  // 1. Try Gemini AI Text-To-Speech (TTS) for natural regional voice pronunciation
  try {
    const res = await fetch('/api/ai/tts', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text, langName }),
    });

    if (res.ok) {
      const json = await res.json();
      if (json.success && json.audio) {
        await playBase64AudioPcm(json.audio);
        if (onEnd) onEnd();
        return;
      }
    }
  } catch (err) {
    console.warn('AI TTS request failed, using browser speech synthesis fallback:', err);
  }

  // 2. Fallback to client Web Speech API
  fallbackSpeechSynthesis(text, langCode, onEnd);
}

/**
 * Play 24kHz 16-bit PCM Audio generated by Gemini TTS
 */
function playBase64AudioPcm(base64Audio: string, sampleRate = 24000): Promise<void> {
  return new Promise((resolve) => {
    try {
      const binaryString = atob(base64Audio);
      const len = binaryString.length;
      const bytes = new Uint8Array(len);
      for (let i = 0; i < len; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }

      const AudioContextClass = window.AudioContext || (window as any).webkitAudioContext;
      if (!AudioContextClass) {
        resolve();
        return;
      }

      const ctx = new AudioContextClass({ sampleRate });
      const int16Array = new Int16Array(bytes.buffer);
      const buffer = ctx.createBuffer(1, int16Array.length, sampleRate);
      const channelData = buffer.getChannelData(0);

      for (let i = 0; i < int16Array.length; i++) {
        channelData[i] = int16Array[i] / 32768.0;
      }

      const source = ctx.createBufferSource();
      source.buffer = buffer;
      source.connect(ctx.destination);

      source.onended = () => {
        try {
          ctx.close();
        } catch (e) {
          // ignore
        }
        resolve();
      };

      source.start(0);
    } catch (err) {
      console.warn('Failed to decode/play PCM audio:', err);
      resolve();
    }
  });
}

/**
 * Fallback Speech Synthesis using Browser Web Speech API
 */
function fallbackSpeechSynthesis(text: string, langCode: string = 'id-ID', onEnd?: () => void): void {
  if (!('speechSynthesis' in window)) {
    playSynthesizedChime();
    if (onEnd) onEnd();
    return;
  }

  window.speechSynthesis.cancel();

  const utterance = new SpeechSynthesisUtterance(text);
  utterance.rate = 0.85; // Slightly slower for clear regional pronunciation
  utterance.pitch = 1.0;

  const voices = window.speechSynthesis.getVoices();
  const selectedVoice = voices.find(v => v.lang.startsWith(langCode) || v.lang.startsWith('id')) || voices[0];
  if (selectedVoice) {
    utterance.voice = selectedVoice;
  }

  utterance.onend = () => {
    if (onEnd) onEnd();
  };

  utterance.onerror = () => {
    playSynthesizedChime();
    if (onEnd) onEnd();
  };

  window.speechSynthesis.speak(utterance);
}

/**
 * Fallback Web Audio chime tone for visual/auditory feedback
 */
export function playSynthesizedChime(): void {
  try {
    const AudioContextClass = window.AudioContext || (window as any).webkitAudioContext;
    if (!AudioContextClass) return;

    const ctx = new AudioContextClass();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();

    osc.type = 'sine';
    osc.frequency.setValueAtTime(523.25, ctx.currentTime); // C5
    osc.frequency.exponentialRampToValueAtTime(659.25, ctx.currentTime + 0.15); // E5

    gain.gain.setValueAtTime(0.15, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.3);

    osc.connect(gain);
    gain.connect(ctx.destination);

    osc.start();
    osc.stop(ctx.currentTime + 0.3);
  } catch (e) {
    // Ignore context blocked
  }
}
